---
- hosts: windows
  tasks:
  - name: Install Active Directory Services
    win_feature:
      name: AD-Domain-Services
      include_management_tools: yes
      include_sub_features: yes
      state: present
    register: result

  - name: Create the forest
    win_domain:
      dns_domain_name: it385.local
      safe_mode_password: passWord01
    register: result

  - name: Restart machine
    win_reboot:
      msg: "Restarting Machine, Do not turn off Power."
    when: result.reboot_required
  